### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by simon-p-r** [continuationlabs/hapi-setup#7]
I currently use something similar internally within my company however it maybe better to contribute to this project instead.  So my question is can we split the object into separate routes rather than one large object.

Thanks
Simon

**Comment by arb** [comment]
Since this is a plugin method, you are free to break the result up however you want. If you want show a list of JUST plugins on a plugin route, that could look something like this:

``` js
server.route({
  method: 'GET',
  path: '/plugins',
  handler: function (request, reply) {
    var data = request.plugins['hapi-setup'].setup();
    var result = data.connections.map(function (i, con) {
      return Object.keys(con.plugins);
    }
    result = result.join(',');
    reply(result);
  }
});
```

The result of `setup()` is a new instance and we clone all the object values so you are free to edit them as you see fit. Also, making the result object composable like you are asking wouldn't have the cleanest api.

**Comment by simon-p-r** [comment]
Sure I agree about api, I will try using and let you know if I have any more questions!
